# Generated by Django 4.2.5 on 2023-12-20 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType_Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default=None, max_length=100, null=True)),
                ('title', models.CharField(max_length=100, unique='title')),
                ('description', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=0)),
                ('adv_booking', models.IntegerField(default=0, null=True)),
                ('lim_booking', models.IntegerField(default=0, null=True)),
                ('cancel_fee', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='facility_mainrules',
            name='points',
        ),
        migrations.RemoveField(
            model_name='facility_mainrules_set',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules',
            name='num_attendies',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules',
            name='num_pc',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules_set',
            name='num_attendies',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules_set',
            name='num_pc',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules_set',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usertype_mainrules_set',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules',
            name='new_rate',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules_set',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules_set',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules_set',
            name='new_rate',
        ),
        migrations.RemoveField(
            model_name='usertype_promorules_set',
            name='start_date',
        ),
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='num_attendies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='num_pc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='facility',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facility_promorules',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='facility_promorules',
            name='is_expired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='facility_promorules_set',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility_promorules_set',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype_mainrules',
            name='adv_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_mainrules',
            name='cancel_fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_mainrules',
            name='lim_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_mainrules_set',
            name='adv_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_mainrules_set',
            name='cancel_fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_mainrules_set',
            name='lim_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules',
            name='adv_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules',
            name='cancel_fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usertype_promorules',
            name='is_expired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usertype_promorules',
            name='lim_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='adv_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='cancel_fee',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='is_available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='is_expired',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='lim_booking',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facility_promorules_set',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='facility_promorules_set',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertype_mainrules_set',
            name='title',
            field=models.CharField(max_length=100, unique='title'),
        ),
        migrations.AlterField(
            model_name='usertype_promorules',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usertype_promorules',
            name='title',
            field=models.CharField(max_length=100, unique='title'),
        ),
        migrations.AlterField(
            model_name='usertype_promorules_set',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usertype_promorules_set',
            name='title',
            field=models.CharField(max_length=100, unique='title'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
