# Generated by Django 4.2.5 on 2023-12-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_usertype_rules_remove_facility_mainrules_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype_promorules',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='usertype_promorules_set',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='setting_usertype',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.usertype_rules'),
        ),
        migrations.AlterField(
            model_name='usertype_rules',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
