# Generated by Django 4.2.6 on 2023-12-19 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0109_alter_facility_promorules_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('computers', models.IntegerField(null=True)),
                ('hasComputers', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookDate', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('purpose', models.CharField(default='Studying', max_length=50)),
                ('coins', models.FloatField(default=0)),
                ('points', models.FloatField(default=0)),
                ('computers', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=100, null=True)),
                ('isUsed', models.BooleanField(default=False, null=True)),
                ('duration', models.FloatField(default=0)),
                ('referenceNo', models.TextField(blank=True, default=uuid.uuid1, max_length=8, unique=True)),
                ('officeName', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(default='Booked', max_length=20, null=True)),
                ('venueName', models.CharField(max_length=50, null=True)),
                ('isOverstayingCharged', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booker', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='facility.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('rfid', models.CharField(max_length=30, null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfid', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('signInTime', models.TimeField(null=True)),
                ('signOutTime', models.TimeField(default=None, null=True)),
                ('isOverstaying', models.BooleanField(default=False, null=True)),
                ('isSignedIn', models.BooleanField(default=False, null=True)),
                ('venueName', models.CharField(max_length=50, null=True)),
                ('venueId', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(default=0, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.booking')),
            ],
        ),
    ]
