# Generated by Django 4.2.5 on 2023-12-21 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='referenceNo',
            field=models.CharField(blank=True, default=uuid.uuid1, max_length=20, unique=True),
        ),
    ]
