# Generated by Django 4.2.5 on 2023-12-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_user_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='point_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='points_to_give',
            field=models.FloatField(default=0.0),
        ),
    ]
