# Generated by Django 4.2.5 on 2023-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='coin_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
