# Generated by Django 4.2.5 on 2023-12-19 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_userprofileinfo_coin_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
