# Generated by Django 4.2.5 on 2023-12-21 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorTransaction',
            fields=[
                ('reference_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('venueName', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('BookDate', models.DateField(null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('purpose', models.CharField(default='Studying', max_length=50)),
                ('computers', models.IntegerField(default=0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('currency', models.CharField(choices=[('points', 'Points'), ('coins', 'Coins')], default='coins', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
